name: ⌨️ Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-jar:
    name: 'Build JAR package'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'gradle'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: java-binary
          path: |
            ${{ github.workspace }}/build/libs/*-all.jar
          retention-days: 30
  build-native-image:
    name: Native image build on ${{ matrix.os }} and Java ${{ matrix.jdk-version }}
    needs: [ build-jar ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        graalvm-version: ['22.0.0.2']
        jdk-version: ['17']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Download application package
        uses: actions/download-artifact@v2
        with:
          name: java-binary
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.jdk-version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native image on Linux
        run: native-image --static -jar trip-calculator-*-all.jar trip-calculator-linux --no-fallback
        if: runner.os == 'Linux'
      - name: Build native image on Mac OS X
        run: native-image -jar trip-calculator-*-all.jar trip-calculator-macos --no-fallback
        if: runner.os == 'macOS'
      - name: Build native image on Windows
        run: native-image -jar trip-calculator-*-all.jar trip-calculator-windows --no-fallback
        if: runner.os == 'Windows'
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: trip-calculator-${{ matrix.os }}-java-${{ matrix.jdk-version }}
          path: |
            trip-calculator-*
            !*.txt
            !*.jar
          retention-days: 30
