name: ⌨️ Continuous Integration
on:
  push:
    branches:
      - quarkus
  pull_request:
    branches:
      - quarkus
jobs:
  build-jar:
    name: 'Build JAR package'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: 'gradle'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: trip-calculator-java
          path: |
            ${{ github.workspace }}/build/trip-calculator-*-runner.jar
          retention-days: 30
  build-native-image:
    name: Native image build on ${{ matrix.os }} and Java ${{ matrix.jdk-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        graalvm-version: ['22.0.0.2']
        jdk-version: ['17']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.jdk-version }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native image on ${{ runner.os }}
        run: './gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=false -x test'
        if: runner.os != 'Windows'
      - name: Build native image on Windows
        run: .\gradlew build "-Dquarkus.package.type=native" "-Dquarkus.native.container-build=false" -x test
        if: runner.os == 'Windows'
      - name: Temporarily save package
        uses: actions/upload-artifact@v2
        with:
          name: trip-calculator-${{ matrix.os }}
          path: |
            build/trip-calculator-*
            !*.jar
          retention-days: 30
